
ALTER GIT REPOSITORY SLINGSHOT_TEMP.SETUP.SNOWFLAKE_PLATFORM_REPO FETCH;

-- Then update tasks to use Git stage
CREATE OR REPLACE TASK SLINGSHOT_TEMP.SETUP.RUN_TEST1_SQL
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 9 * * * America/Los_Angeles'
  AS
  EXECUTE IMMEDIATE FROM @SLINGSHOT_TEMP.SETUP.SNOWFLAKE_PLATFORM_REPO/branches/main/team1/sqls/test1.sql;


CREATE OR REPLACE TASK SLINGSHOT_TEMP.SETUP.RUN_TEST2_SQL
  WAREHOUSE = COMPUTE_WH
  AFTER SLINGSHOT_TEMP.SETUP.RUN_TEST1_SQL
  AS
  EXECUTE IMMEDIATE FROM @SLINGSHOT_TEMP.SETUP.SNOWFLAKE_PLATFORM_REPO/branches/main/team1/sqls/test2.sql